### ISSUE TITLE
[bug]聚合搜索结果没有过滤掉无效url结果

### ISSUE THREAD

**Issue by ywgATustcbbs** [jadepeng/XMusicDownloader#15]
在所有的provider的视线里面，当调用SearchSongs等函数时候，执行了result.Add(song);讲可用搜索结果添加到列表中供用户下载。但是当搜索结果为版权或收费歌曲时，后续调用getDownloadUrl(song);将得到null的url，这使得后续无法下载。

修改建议：建议将所有的result.Add(song);替换为如下代码。在索索结果呈现前过滤掉无法下载的结果。
song.url = getDownloadUrl(song);
                    if (song.url != null && song.url != "" && song.url.ToLower().StartsWith("http"))
                    {
                        result.Add(song);
                    }

**Comment by ywgATustcbbs** [comment]
我的天，我刚才烦了一下issue，这bug去年就有了，这么久了都没修掉么……

**Comment by jadepeng** [comment]
一直没空看这个，刚已修复
下次可以提交pr
